services:
  fastapi:
    image: kcheid/house-price--model:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  streamlit:
    image: kcheid/streamlit:latest 
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    environment:
      API_URL: http://model:8000

